TARGET = iphone:10.1:10.0

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = Canzone
Canzone_FILES = main.m
Canzone_FRAMEWORKS = UIKit
Canzone_ARCHS = armv7

include $(THEOS_MAKE_PATH)/application.mk
