include $(THEOS)/makefiles/common.mk

TOOL_NAME = postinst

postinst_FILES = postinst.swift
postinst_INSTALL_PATH = /DEBIAN
postinst_SWIFT_BRIDGING_HEADER = BridgingHeader.h

include $(THEOS_MAKE_PATH)/tool.mk
